import { Router } from 'express';
import authRoutes from './authRoutes.js';
import catalogRoutes from './catalogRoutes.js';
import questionRoutes from './questionRoutes.js';
import syllabusRoutes from './syllabusRoutes.js';
import questionBankRoutes from './questionBankRoutes.js';
import uploadRoutes from './uploadRoutes.js';
import paperRoutes from './paperRoutes.js';
import testRoutes from './testRoutes.js';
import analyticsRoutes from './analyticsRoutes.js';
import leaderboardRoutes from './leaderboardRoutes.js';
import userRoutes from './userRoutes.js';
import examTemplateRoutes from './examTemplateRoutes.js';
import exportPresetRoutes from './exportPresetRoutes.js';
import institutionProfileRoutes from './institutionProfileRoutes.js';
import documentClassificationRoutes from './documentClassification.js';
import { health, readiness } from '../controllers/healthController.js';
import institutionRoutes from './institutionRoutes.js';

const router = Router();

router.get('/health', health);
router.get('/ready', readiness);
router.use('/auth', authRoutes);
router.use('/institutions', institutionRoutes);
router.use('/questions', questionRoutes);
router.use('/syllabus', syllabusRoutes);
router.use('/question-banks', questionBankRoutes);
router.use('/uploads', uploadRoutes);
router.use('/papers', paperRoutes);
router.use('/tests', testRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/leaderboard', leaderboardRoutes);
router.use('/users', userRoutes);
router.use('/exam-templates', examTemplateRoutes);
router.use('/export-presets', exportPresetRoutes);
router.use('/institution-profiles', institutionProfileRoutes);
router.use('/document-classification', documentClassificationRoutes);
router.use('/', catalogRoutes);

export default router;
